//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace compuSciProj2021.JobsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="jobsServiceSoap", Namespace="http://tempuri.org/")]
    public partial class jobsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApplyingUsrsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetjobsOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsntRelevantOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertUsrOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertAplctnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCitisOperationCompleted;
        
        private System.Threading.SendOrPostCallback findwrkplceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsrInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback WrkplceByOffrOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRplyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public jobsService() {
            this.Url = global::compuSciProj2021.Properties.Settings.Default.compuSciProj2021_JobsService_jobsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetApplyingUsrsCompletedEventHandler GetApplyingUsrsCompleted;
        
        /// <remarks/>
        public event GetjobsCompletedEventHandler GetjobsCompleted;
        
        /// <remarks/>
        public event IsntRelevantCompletedEventHandler IsntRelevantCompleted;
        
        /// <remarks/>
        public event InsertUsrCompletedEventHandler InsertUsrCompleted;
        
        /// <remarks/>
        public event InsertAplctnCompletedEventHandler InsertAplctnCompleted;
        
        /// <remarks/>
        public event GetCitisCompletedEventHandler GetCitisCompleted;
        
        /// <remarks/>
        public event findwrkplceCompletedEventHandler findwrkplceCompleted;
        
        /// <remarks/>
        public event GetUsrInfoCompletedEventHandler GetUsrInfoCompleted;
        
        /// <remarks/>
        public event WrkplceByOffrCompletedEventHandler WrkplceByOffrCompleted;
        
        /// <remarks/>
        public event UpdateRplyCompletedEventHandler UpdateRplyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApplyingUsrs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetApplyingUsrs(Workplace w) {
            object[] results = this.Invoke("GetApplyingUsrs", new object[] {
                        w});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetApplyingUsrsAsync(Workplace w) {
            this.GetApplyingUsrsAsync(w, null);
        }
        
        /// <remarks/>
        public void GetApplyingUsrsAsync(Workplace w, object userState) {
            if ((this.GetApplyingUsrsOperationCompleted == null)) {
                this.GetApplyingUsrsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApplyingUsrsOperationCompleted);
            }
            this.InvokeAsync("GetApplyingUsrs", new object[] {
                        w}, this.GetApplyingUsrsOperationCompleted, userState);
        }
        
        private void OnGetApplyingUsrsOperationCompleted(object arg) {
            if ((this.GetApplyingUsrsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApplyingUsrsCompleted(this, new GetApplyingUsrsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getjobs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Getjobs() {
            object[] results = this.Invoke("Getjobs", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetjobsAsync() {
            this.GetjobsAsync(null);
        }
        
        /// <remarks/>
        public void GetjobsAsync(object userState) {
            if ((this.GetjobsOperationCompleted == null)) {
                this.GetjobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetjobsOperationCompleted);
            }
            this.InvokeAsync("Getjobs", new object[0], this.GetjobsOperationCompleted, userState);
        }
        
        private void OnGetjobsOperationCompleted(object arg) {
            if ((this.GetjobsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetjobsCompleted(this, new GetjobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsntRelevant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsntRelevant(int offerNum) {
            this.Invoke("IsntRelevant", new object[] {
                        offerNum});
        }
        
        /// <remarks/>
        public void IsntRelevantAsync(int offerNum) {
            this.IsntRelevantAsync(offerNum, null);
        }
        
        /// <remarks/>
        public void IsntRelevantAsync(int offerNum, object userState) {
            if ((this.IsntRelevantOperationCompleted == null)) {
                this.IsntRelevantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsntRelevantOperationCompleted);
            }
            this.InvokeAsync("IsntRelevant", new object[] {
                        offerNum}, this.IsntRelevantOperationCompleted, userState);
        }
        
        private void OnIsntRelevantOperationCompleted(object arg) {
            if ((this.IsntRelevantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsntRelevantCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUsr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertUsr(User u) {
            this.Invoke("InsertUsr", new object[] {
                        u});
        }
        
        /// <remarks/>
        public void InsertUsrAsync(User u) {
            this.InsertUsrAsync(u, null);
        }
        
        /// <remarks/>
        public void InsertUsrAsync(User u, object userState) {
            if ((this.InsertUsrOperationCompleted == null)) {
                this.InsertUsrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUsrOperationCompleted);
            }
            this.InvokeAsync("InsertUsr", new object[] {
                        u}, this.InsertUsrOperationCompleted, userState);
        }
        
        private void OnInsertUsrOperationCompleted(object arg) {
            if ((this.InsertUsrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUsrCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertAplctn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertAplctn(Application A) {
            this.Invoke("InsertAplctn", new object[] {
                        A});
        }
        
        /// <remarks/>
        public void InsertAplctnAsync(Application A) {
            this.InsertAplctnAsync(A, null);
        }
        
        /// <remarks/>
        public void InsertAplctnAsync(Application A, object userState) {
            if ((this.InsertAplctnOperationCompleted == null)) {
                this.InsertAplctnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertAplctnOperationCompleted);
            }
            this.InvokeAsync("InsertAplctn", new object[] {
                        A}, this.InsertAplctnOperationCompleted, userState);
        }
        
        private void OnInsertAplctnOperationCompleted(object arg) {
            if ((this.InsertAplctnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertAplctnCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCitis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCitis() {
            object[] results = this.Invoke("GetCitis", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCitisAsync() {
            this.GetCitisAsync(null);
        }
        
        /// <remarks/>
        public void GetCitisAsync(object userState) {
            if ((this.GetCitisOperationCompleted == null)) {
                this.GetCitisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCitisOperationCompleted);
            }
            this.InvokeAsync("GetCitis", new object[0], this.GetCitisOperationCompleted, userState);
        }
        
        private void OnGetCitisOperationCompleted(object arg) {
            if ((this.GetCitisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCitisCompleted(this, new GetCitisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/findwrkplce", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet findwrkplce(User u) {
            object[] results = this.Invoke("findwrkplce", new object[] {
                        u});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void findwrkplceAsync(User u) {
            this.findwrkplceAsync(u, null);
        }
        
        /// <remarks/>
        public void findwrkplceAsync(User u, object userState) {
            if ((this.findwrkplceOperationCompleted == null)) {
                this.findwrkplceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindwrkplceOperationCompleted);
            }
            this.InvokeAsync("findwrkplce", new object[] {
                        u}, this.findwrkplceOperationCompleted, userState);
        }
        
        private void OnfindwrkplceOperationCompleted(object arg) {
            if ((this.findwrkplceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findwrkplceCompleted(this, new findwrkplceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsrInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUsrInfo(User u) {
            object[] results = this.Invoke("GetUsrInfo", new object[] {
                        u});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsrInfoAsync(User u) {
            this.GetUsrInfoAsync(u, null);
        }
        
        /// <remarks/>
        public void GetUsrInfoAsync(User u, object userState) {
            if ((this.GetUsrInfoOperationCompleted == null)) {
                this.GetUsrInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsrInfoOperationCompleted);
            }
            this.InvokeAsync("GetUsrInfo", new object[] {
                        u}, this.GetUsrInfoOperationCompleted, userState);
        }
        
        private void OnGetUsrInfoOperationCompleted(object arg) {
            if ((this.GetUsrInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsrInfoCompleted(this, new GetUsrInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WrkplceByOffr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WrkplceByOffr(int offerNum) {
            object[] results = this.Invoke("WrkplceByOffr", new object[] {
                        offerNum});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WrkplceByOffrAsync(int offerNum) {
            this.WrkplceByOffrAsync(offerNum, null);
        }
        
        /// <remarks/>
        public void WrkplceByOffrAsync(int offerNum, object userState) {
            if ((this.WrkplceByOffrOperationCompleted == null)) {
                this.WrkplceByOffrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWrkplceByOffrOperationCompleted);
            }
            this.InvokeAsync("WrkplceByOffr", new object[] {
                        offerNum}, this.WrkplceByOffrOperationCompleted, userState);
        }
        
        private void OnWrkplceByOffrOperationCompleted(object arg) {
            if ((this.WrkplceByOffrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WrkplceByOffrCompleted(this, new WrkplceByOffrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRply", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateRply(Application a) {
            this.Invoke("UpdateRply", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void UpdateRplyAsync(Application a) {
            this.UpdateRplyAsync(a, null);
        }
        
        /// <remarks/>
        public void UpdateRplyAsync(Application a, object userState) {
            if ((this.UpdateRplyOperationCompleted == null)) {
                this.UpdateRplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRplyOperationCompleted);
            }
            this.InvokeAsync("UpdateRply", new object[] {
                        a}, this.UpdateRplyOperationCompleted, userState);
        }
        
        private void OnUpdateRplyOperationCompleted(object arg) {
            if ((this.UpdateRplyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRplyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Workplace {
        
        private string phoneField;
        
        private string idField;
        
        private string addrsField;
        
        private string nameField;
        
        private int cityField;
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Addrs {
            get {
                return this.addrsField;
            }
            set {
                this.addrsField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Application {
        
        private string userIdField;
        
        private string workIdField;
        
        private string replyField;
        
        private string cvField;
        
        private int offerNumberField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string WorkId {
            get {
                return this.workIdField;
            }
            set {
                this.workIdField = value;
            }
        }
        
        /// <remarks/>
        public string Reply {
            get {
                return this.replyField;
            }
            set {
                this.replyField = value;
            }
        }
        
        /// <remarks/>
        public string Cv {
            get {
                return this.cvField;
            }
            set {
                this.cvField = value;
            }
        }
        
        /// <remarks/>
        public int offerNumber {
            get {
                return this.offerNumberField;
            }
            set {
                this.offerNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private string phoneNumField;
        
        private string phoneField;
        
        private string idField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string addrsField;
        
        private string mAddrsField;
        
        private int cityField;
        
        /// <remarks/>
        public string phoneNum {
            get {
                return this.phoneNumField;
            }
            set {
                this.phoneNumField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string Addrs {
            get {
                return this.addrsField;
            }
            set {
                this.addrsField = value;
            }
        }
        
        /// <remarks/>
        public string mAddrs {
            get {
                return this.mAddrsField;
            }
            set {
                this.mAddrsField = value;
            }
        }
        
        /// <remarks/>
        public int City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetApplyingUsrsCompletedEventHandler(object sender, GetApplyingUsrsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApplyingUsrsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApplyingUsrsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetjobsCompletedEventHandler(object sender, GetjobsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetjobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetjobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IsntRelevantCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void InsertUsrCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void InsertAplctnCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCitisCompletedEventHandler(object sender, GetCitisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCitisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCitisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void findwrkplceCompletedEventHandler(object sender, findwrkplceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findwrkplceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findwrkplceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUsrInfoCompletedEventHandler(object sender, GetUsrInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsrInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsrInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void WrkplceByOffrCompletedEventHandler(object sender, WrkplceByOffrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WrkplceByOffrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WrkplceByOffrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UpdateRplyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591